name: Run build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.properties.outputs.version }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      # SEE: [rust-cache/.github/workflows/simple.yml at master · Swatinem/rust-cache](https://github.com/Swatinem/rust-cache/blob/master/.github/workflows/simple.yml)
      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "app"

      # Enable Docker build cache
      # So now you can use Actions' own caching!
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.target }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-buildx-

      # TODO: Cache build/cache "dir"

      - name: Run Dagger pipeline
        run: |
          if [ '${{ matrix.target }}' = 'aarch64-unknown-linux-musl' ]; then
            cargo run -- arm64_linux
          else
            cargo run -- x64_linux
          fi
          # Copy bin to "dist"
          mkdir -p ../dist
          cp -rf ./bin/* ../dist
        working-directory: ./build
      - name: Export properties
        id: properties
        run: |
          VERSION="$(cat ./dist/${{ matrix.target }}/version.txt)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.target }}-${{steps.properties.outputs.version}}
          path: |
            dist

      # This ugly bit is necessary if you don't want your cache to grow forever
      # until it hits GitHub's limit of 5GB.
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        shell: bash
        run: |
          # Run only if build cache exists.
          if [ -d "/tmp/.buildx-cache-new" ] 
          then
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          fi