name: Run build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    outputs:
      version: ${{ steps.properties.outputs.version }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/checkout@v3

      # SEE: [crazy-max/ghaction-github-runtime: :octocat: GitHub Action to expose GitHub runtime to the workflow](https://github.com/crazy-max/ghaction-github-runtime)
      # SEE: [GitHub Actions cache | Docker Documentation](https://docs.docker.com/build/cache/backends/gha/#authentication)
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      # Enable build cache
      - name: Cache Build caches
        uses: actions/cache@v3
        with:
          path: build/cache
          key: ${{ runner.os }}-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-

      - name: Install deps
        run: |
          yarn install --frozen-lockfile
        working-directory: ./build
      - name: Set BUILDKIT_HOST env
        run: |
          # Try experimental GHA cache support.
          # SEE: [Initial support for remote cache config. by sipsma · Pull Request #4543 · dagger/dagger](https://github.com/dagger/dagger/pull/4543)
          echo "_EXPERIMENTAL_DAGGER_CACHE_CONFIG=type=gha,mode=max,scope=dagger-gha-cache" >> $GITHUB_ENV
      - name: Run Dagger pipeline
        run: |
          yarn build -t ${{ matrix.target }}
        working-directory: ./build
      - name: Export properties
        id: properties
        run: |
          VERSION="$(cat ./dist/${{ matrix.target }}/version.txt)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.target }}-${{steps.properties.outputs.version}}
          path: |
            dist